site_name: 'Hypermake'
site_description: 'Parameterized workflow manager'
site_author: 'Tongfei Chen'
copyright: 'Copyright &copy; 2020-2021 Tongfei Chen'


theme:
  name: material
  palette:
    scheme: default
    primary: 'blue grey'
    accent: grey

repo_name: 'ctongfei/hypermake'
repo_url: 'https://github.com/ctongfei/hypermake'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Introduction': 'index.md'
  - 'Tutorial':
      - "01 Hello, world!": 'tutorial/01-hello.md'
      - "02 Inputs & outputs": 'tutorial/02-compose.md'
      - "03 Parameters": 'tutorial/03-branch.md'
